### ISSUE TITLE
snRNA-seq data location

### ISSUE THREAD

**Issue by onahman** [spacetx-spacejam/data#16]
Hi,
The publication says:
_smFISH data, Visium VISp data, MERFISH VISp data and Smart-Seq2 VISp snRNA-seq data are available at http://github.com/spacetx-spacejam/data._

I can't find the snRNA-seq data.
Where can I download it from?
Thank you!

**Comment by berl** [comment]
thanks for catching this @onahman, we're on it!

**Comment by berl** [comment]
this won't be the final method for accessing the data, but for now you can get the scRNASeq data [here](https://www.dropbox.com/sh/q687ajyvnkbtwkc/AACxlJAsJaJ5DVe-2mx3cbW2a?dl=0)

and I added the cluster information [here](https://github.com/spacetx-spacejam/data/blob/master/mouseVISp_cluster_summary.csv)

**Comment by onahman** [comment]
Thank you very much for the quick reply and solution!

**Comment by Smilenone** [comment]
> this won't be the final method for accessing the data, but for now you can get the scRNASeq data [here](https://www.dropbox.com/sh/q687ajyvnkbtwkc/AACxlJAsJaJ5DVe-2mx3cbW2a?dl=0)
> 
> and I added the cluster information [here](https://github.com/spacetx-spacejam/data/blob/master/mouseVISp_cluster_summary.csv)

Thanks for your solution. I found exon.counts and intron.counts in dropbox. If I would like to integration  scRNASeq and the MERFISH VISp data, which one should I use? (exon or intron)?

**Comment by berl** [comment]
@Smilenone  in this case the spatial data has probes targeting exons only, so that's likely the data with the best correspondence.
