### ISSUE TITLE
smFISH dataset Cell*Genes Data

### ISSUE THREAD

**Issue by cindyway** [spacetx-spacejam/data#17]
Hi, 
I see the Tangram paper quotes the 4840 spots and gene data can be downloaded here. However, I cannot find any correspondence dataset. 
Another question is that the paper mentioned that the MERFISH has 4951 spots. But when I downloaded the dataset, there were only 2399 cells/spots.
How I can get the correct dataset as the paper mentioned?

**Comment by berl** [comment]
hi @cindyway  I think these are referring to rows 8 (Allen MERFISH) and 9 (Allen smFISH) in the readme.md of this repo.  but they also used the MERFISH MOp data from Xiaowei Zhuang's lab and provide a link for that:  https://doi.brainimagelibrary.org/doi/10.35077/g.21, so that may also be relevant.

**Comment by cindyway** [comment]
Thank you so much for the quick response! Yes, but I am also confused about the row 9 data: where is the smFISH 4840 spots*genes expression?

**Comment by berl** [comment]
hi @cindyway, check out this page from our project page that has cell x gene data for the smFISH
https://spacetx.github.io/data.html

**Comment by cindyway** [comment]
Thank you for your quick response and all the work :)
